name: Android CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

permissions:
  contents: read

env:
  JAVA_VERSION: "17"
  ANDROID_API_LEVEL: "34"
  ANDROID_BUILD_TOOLS: "34.0.0"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build-and-unit-test:
    name: Build & Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install build tools and platforms
        run: |
          sdkmanager "platform-tools" "platforms;android-${{ env.ANDROID_API_LEVEL }}" "build-tools;${{ env.ANDROID_BUILD_TOOLS }}"
          yes | sdkmanager --licenses

      - name: Gradle Build (assemble + unit tests + lint)
        uses: gradle/gradle-build-action@v3
        with:
            arguments: |
              clean
              build
              test
              lint
            gradle-home-cache-includes: |
              caches
              notifications
              jdks
              wrapper

      - name: Upload unit test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-reports
          path: |
            **/build/test-results/test/**/*
            **/build/reports/tests/test/**/*
            **/build/reports/lint-results*.*

  instrumented-tests:
    name: Instrumented Tests (Emulator)
    runs-on: ubuntu-latest
    needs: build-and-unit-test
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: gradle

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install build tools and platforms
        run: |
          sdkmanager "platform-tools" "platforms;android-${{ env.ANDROID_API_LEVEL }}" "build-tools;${{ env.ANDROID_BUILD_TOOLS }}"
          yes | sdkmanager --licenses

      - name: Launch emulator and run connected tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ env.ANDROID_API_LEVEL }}
          arch: x86_64
          target: default
          profile: pixel_6
          script: |
            ./gradlew --no-daemon clean assembleDebug
            ./gradlew --no-daemon connectedDebugAndroidTest

      - name: Upload instrumented test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: androidTest-reports
          path: |
            **/build/reports/androidTests/connected/**/*
            **/build/outputs/androidTest-results/**/*
            **/build/outputs/managed_device_android_test_results/**/*
